name: CI – Run Qwen3-Coder

on:
  push:
    branches: [ main ]
    paths:
      - 'scripts/llama_cpp_setup.sh'
      - 'Dockerfile'
      - '.github/workflows/run_qwen.yml'
  workflow_dispatch: {}

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python deps
        run: |
          pip install --upgrade pip
          pip install huggingface_hub hf_transfer transformers

      - name: Build llama.cpp
        run: bash scripts/llama_cpp_setup.sh

      # Run these heavy steps *only* on manual dispatch
      - name: Download Qwen3 model
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: python scripts/model_download.py

      - name: Run Qwen inference script
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: bash scripts/run_qwen.sh

