on:
  push:
    paths:
      - 'scripts/llama_cpp_setup.sh'
      - 'scripts/run_qwen.sh'
      - 'scripts/model_download.py'
      - 'scripts/tool_calling_example.py'
      - 'Dockerfile'
      - '.github/workflows/run_qwen.yml'

jobs:
  build-and-run:
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: { python-version: '3.10' }
      - run: |
          pip install --upgrade pip
          pip install huggingface_hub hf_transfer transformers
      - run: python scripts/model_download.py
      - run: bash scripts/llama_cpp_setup.sh
      - run: bash scripts/run_qwen.sh

